/**
 * Project Consciousness — generates a living CONTINUUM.md for each project.
 *
 * Uses Claude CLI to synthesize all stored memories into a structured
 * context document that gets auto-loaded by Claude Code, Cursor, etc.
 * Zero cloud. Uses the subscription you already have.
 */

import { spawnSync } from "child_process";
import { writeFileSync, mkdirSync, existsSync } from "fs";
import { join } from "path";
import type { Database } from "bun:sqlite";
import { getContext, countMemories } from "./db.js";

const SNAPSHOT_PROMPT = (project: string, memories: string[]) => `
You are generating a project context document for a developer.

Project: ${project}
Memories and decisions (${memories.length} total):
${memories.join("\n")}

Generate a concise markdown document titled "# ${project} — Project Context" with these sections:

## Architecture
Key technology choices, stack, and infrastructure decisions.

## Conventions & Patterns
Coding patterns and conventions established in this project.

## Recent Decisions
The most important recent architectural/technical decisions and WHY they were made.

## Known Gotchas
Non-obvious traps, limitations, or things to avoid.

## Active Context
What's currently being worked on / recent focus areas.

Rules:
- Under 600 words total
- Be specific, not generic
- Focus on WHY decisions were made, not just what they are
- Write for a developer who knows the codebase but forgot the context
- NEVER include secrets, credentials, or sensitive data
- Output ONLY the markdown document, nothing else
`.trim();

export async function generateSnapshot(
  project: string,
  projectPath: string,
  db: Database,
  claudeBin: string,
  model: string
): Promise<{ markdown: string; path: string } | null> {
  const total = countMemories(db, project);
  if (total === 0) return null;

  // Get most recent 80 memories for synthesis
  const memories = getContext(db, project, 80);

  const env: Record<string, string | undefined> = { ...process.env };
  delete env["CLAUDECODE"];
  delete env["CLAUDE_CODE"];

  const result = spawnSync(claudeBin, ["-p", "--model", model], {
    input: SNAPSHOT_PROMPT(project, memories),
    encoding: "utf8",
    timeout: 90_000,
    env: env as NodeJS.ProcessEnv,
    maxBuffer: 2 * 1024 * 1024,
  });

  if (result.status !== 0 || !result.stdout?.trim()) return null;

  const markdown = result.stdout.trim();

  // Write to project root as CONTINUUM.md (auto-loaded by Claude Code)
  const snapshotPath = join(projectPath, "CONTINUUM.md");
  if (existsSync(projectPath)) {
    writeFileSync(snapshotPath, `${markdown}\n\n---\n*Generated by [Continuum](https://github.com/continuum-ai/continuum) — ${new Date().toISOString().split("T")[0]}*\n`);
  }

  // Also write to ~/.continuum/snapshots/<project>.md
  const { CONFIG_DIR } = await import("./config.js");
  const snapshotsDir = join(CONFIG_DIR, "snapshots");
  mkdirSync(snapshotsDir, { recursive: true });
  writeFileSync(join(snapshotsDir, `${project}.md`), markdown);

  return { markdown, path: snapshotPath };
}

export async function autoSnapshot(
  project: string,
  projectPath: string,
  db: Database,
  claudeBin: string,
  model: string,
  threshold = 10
): Promise<void> {
  const total = countMemories(db, project);
  // Only snapshot if we have enough memories and it's a round number
  if (total > 0 && total % threshold === 0) {
    await generateSnapshot(project, projectPath, db, claudeBin, model);
  }
}
